/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.publicity.ui.custom;

import com.publicity.utils.ButtonIcon;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Yordanys
 */
public class ActivePanel extends javax.swing.JPanel {

    /**
     * Creates new form ActivePanel
     */
    public ActivePanel() {
        initComponents();
        
        activeButton.setLocation(10, 0);
        linePanel.setLocation(20, 10);
        activeButton.setIcon(normalIcon);
        //jButton2.setBorder(null);  
        activeButton.setBorderPainted(false);  
        activeButton.setContentAreaFilled(false);  
        activeButton.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);  
        activeButton.setDoubleBuffered(true);  
        activeButton.setFocusPainted(false);          
        //jButton2.setRolloverIcon(rolloverIcon);
        //jButton2.setPressedIcon(rolloverIcon);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        activeButton = new javax.swing.JButton();
        linePanel = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(100, 22));
        setPreferredSize(new java.awt.Dimension(100, 22));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        activeButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        activeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                activeButtonMouseReleased(evt);
            }
        });
        activeButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                activeButtonMouseDragged(evt);
            }
        });
        add(activeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        linePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(102, 102, 102)));

        javax.swing.GroupLayout linePanelLayout = new javax.swing.GroupLayout(linePanel);
        linePanel.setLayout(linePanelLayout);
        linePanelLayout.setHorizontalGroup(
            linePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        linePanelLayout.setVerticalGroup(
            linePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(linePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 25, -1));
    }// </editor-fold>//GEN-END:initComponents
    
    private void activeButtonMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_activeButtonMouseDragged
        try {
            int x = getMousePosition().x - (activeButton.getWidth() / 2);
            activeButton.setLocation(x, activeButton.getY());
            if ((x - xx) > 0 && x > 11) {
                activeButton.setLocation(25, activeButton.getY());
                normalIcon.changeStyle(RoundIcon.STYLE.RED);
            }
            if ((x - xx) < 0 && x < 11) {
                activeButton.setLocation(0, activeButton.getY());
                normalIcon.changeStyle(RoundIcon.STYLE.GREEN);
            }
            xx = x;
        } catch (NullPointerException npex) {}
        if (activeButton.getX() > 25)
                activeButton.setLocation(25, activeButton.getY());
        if (activeButton.getX() < 0)
            activeButton.setLocation(0, activeButton.getY());
    }//GEN-LAST:event_activeButtonMouseDragged

    private void activeButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_activeButtonMouseReleased
        if (xx <= 11)
            activeButton.setLocation(0, activeButton.getY());
        else
            activeButton.setLocation(25, activeButton.getY());
    }//GEN-LAST:event_activeButtonMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton activeButton;
    private javax.swing.JPanel linePanel;
    // End of variables declaration//GEN-END:variables
    
    private RoundIcon normalIcon = new RoundIcon(0, RoundIcon.STYLE.GREEN);    
    private RoundIcon rolloverIcon = new RoundIcon(2, RoundIcon.STYLE.GREEN);    

    private int xx = 0;
}
